<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>DIP</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="MCPG.CCA.Util">
			<HintPath>MCPG.CCA.Util.dll</HintPath>
		</Reference>
		<ProjectReference Include="..\DIP.Domain\DIP.Domain.csproj" />
		<ProjectReference Include="..\DIP.Application.Contracts\DIP.Application.Contracts.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="MiniExcel" Version="1.37.0" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="Volo.Abp.BackgroundWorkers.Quartz" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.SettingManagement.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Saas.Host.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.AuditLogging.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.Identity.Pro.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.OpenIddict.Pro.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.Account.Pro.Public.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.Account.Pro.Admin.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.LanguageManagement.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.TextTemplateManagement.Application" Version="9.0.4" />
		<PackageReference Include="Volo.Abp.Gdpr.Application" Version="9.0.4" />
	</ItemGroup>

</Project>
