<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CS8625</NoWarn>
    <Optimize>false</Optimize>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CS8625</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="9.0.0" />
    <PackageReference Include="Blazorise.DataGrid" Version="1.7.4" />
    <PackageReference Include="Blazorise.RichTextEdit" Version="1.7.4" />
    <PackageReference Include="KubernetesClient" Version="18.0.13" />
    <PackageReference Include="PdfSharpCore" Version="1.3.67" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.7.4" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.7.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Twitter" Version="9.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SweetAlertBlazor" Version="1.0.2" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="Volo.Abp.BlobStoring.FileSystem" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DIP.Application\DIP.Application.csproj" />
    <ProjectReference Include="..\DIP.HttpApi\DIP.HttpApi.csproj" />
    <ProjectReference Include="..\DIP.EntityFrameworkCore\DIP.EntityFrameworkCore.csproj" />
    <PackageReference Include="Volo.Abp.Autofac" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Account.Pro.Public.Web.OpenIddict" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Account.Pro.Public.Blazor.Server" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Account.Pro.Admin.Blazor.Server" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Account.Pro.Public.Web.Impersonation" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.AuditLogging.Blazor.Server" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Identity.Pro.Blazor.Server" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.OpenIddict.Pro.Blazor.Server" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.LanguageManagement.Blazor.Server" Version="9.0.4" />
    <PackageReference Include="Volo.Saas.Host.Blazor.Server" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.TextTemplateManagement.Blazor.Server" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Gdpr.Blazor.Server" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX" Version="4.0.5" />
    <PackageReference Include="Volo.Abp.AspNetCore.Components.Server.LeptonXTheme" Version="4.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Pages\**\*.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Pages\**\*.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\NewFolder\" />
    <Folder Include="wwwroot\dipassets\host\media\" />
    <Folder Include="Pages\Site\Directory\" />
    <Folder Include="wwwroot\dipassets\host\MediaFiles\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Pages\Managements\MediaGalleries\EditMediaGalleries.razor" />
    <None Include="Pages\Managements\MediaGalleries\LinkMedias.razor" />
    <None Include="Pages\Managements\MediaGalleries\MediaGalleries.razor" />
    <None Include="Pages\Managements\SiteSetttings\EditSiteSettings.razor" />
    <None Include="wwwroot\assets\.DS_Store" />
    <None Include="wwwroot\assets\css\.DS_Store" />
    <None Include="wwwroot\assets\css\fonts\flexslider-icon.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Black.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Black.woff2" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Bold.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Bold.woff2" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Heavy.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Heavy.woff2" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Light.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Light.woff2" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Medium.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Medium.woff2" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Regular.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Regular.woff2" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Semibold.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Semibold.woff2" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Thin.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Thin.woff2" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Ultralight.svg" />
    <None Include="wwwroot\assets\css\fonts\SFCompactDisplay-Ultralight.woff2" />
    <None Include="wwwroot\assets\css\scss\.DS_Store" />
    <None Include="wwwroot\assets\css\scss\elements\.DS_Store" />
    <None Include="wwwroot\assets\documents\.DS_Store" />
    <None Include="wwwroot\assets\documents\DIP_brochure_2021.pdf" />
    <None Include="wwwroot\assets\js\appear.js" />
    <None Include="wwwroot\assets\js\bootstrap.min.js" />
    <None Include="wwwroot\assets\js\color-scheme.js" />
    <None Include="wwwroot\assets\js\countdown.js" />
    <None Include="wwwroot\assets\js\dip-extension.js" />
    <None Include="wwwroot\assets\js\gmaps.js" />
    <None Include="wwwroot\assets\js\isotope.min.js" />
    <None Include="wwwroot\assets\js\jquery-3.6.0.min.js" />
    <None Include="wwwroot\assets\js\site_V1.js" />
    <None Include="wwwroot\assets\js\site.js" />
    <None Include="wwwroot\assets\js\jquery.countTo.js" />
    <None Include="wwwroot\assets\js\jquery.fancybox.js" />
    <None Include="wwwroot\assets\js\jquery.flexslider-min.js" />
    <None Include="wwwroot\assets\js\jQuery.style.switcher.min.js" />
    <None Include="wwwroot\assets\js\map-helper.js" />
    <None Include="wwwroot\assets\js\owl.js" />
    <None Include="wwwroot\assets\js\sharer.js" />
    <None Include="wwwroot\assets\js\simpleParallax.min.js" />
    <None Include="wwwroot\assets\js\swiper.min.js" />
    <None Include="wwwroot\assets\js\validation.js" />
    <None Include="wwwroot\assets\webfonts\fontawesome-webfont﹖v=4.7.0.svg" />
    <None Include="wwwroot\assets\webfonts\fontawesome-webfont﹖v=4.7.0.woff2" />
    <None Include="wwwroot\assets\webfonts\fonts\icomoon﹖lruvdg.svg" />
    <None Include="wwwroot\assets\webfonts\fonts\star.svg" />
    <None Include="wwwroot\assets\webfonts\fonts\WooCommerce.svg" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Pages\Site\GetDocument\GetDocument.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="wwwroot\assets\css\scss\elements\theme-css-ar.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
