//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakaniNumberService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SIGNUP", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SIGNUP : object
    {
        
        private string AddressField;
        
        private string EmailField;
        
        private string GenderField;
        
        private string LangField;
        
        private string NameField;
        
        private string PasswordField;
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOGIN", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class LOGIN : object
    {
        
        private string EmailField;
        
        private string LangField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FORGETPASSWORD", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class FORGETPASSWORD : object
    {
        
        private string EmailField;
        
        private string LangField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RESETPASSWORD", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class RESETPASSWORD : object
    {
        
        private string EmailField;
        
        private string LangField;
        
        private string OtpField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Otp
        {
            get
            {
                return this.OtpField;
            }
            set
            {
                this.OtpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOGOUT", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class LOGOUT : object
    {
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchInput", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SearchInput : object
    {
        
        private string currentlocationField;
        
        private string distancetypeField;
        
        private string langField;
        
        private string levelField;
        
        private string searchtextField;
        
        private string sessionidField;
        
        private string useridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currentlocation
        {
            get
            {
                return this.currentlocationField;
            }
            set
            {
                this.currentlocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distancetype
        {
            get
            {
                return this.distancetypeField;
            }
            set
            {
                this.distancetypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string searchtext
        {
            get
            {
                return this.searchtextField;
            }
            set
            {
                this.searchtextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sessionid
        {
            get
            {
                return this.sessionidField;
            }
            set
            {
                this.sessionidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResult", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SearchResult : object
    {
        
        private string dgis_idField;
        
        private string featureclass_idField;
        
        private string sessionidField;
        
        private string useridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dgis_id
        {
            get
            {
                return this.dgis_idField;
            }
            set
            {
                this.dgis_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string featureclass_id
        {
            get
            {
                return this.featureclass_idField;
            }
            set
            {
                this.featureclass_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sessionid
        {
            get
            {
                return this.sessionidField;
            }
            set
            {
                this.sessionidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VirtualPlateInput", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class VirtualPlateInput : object
    {
        
        private string currentlocationField;
        
        private string distanceField;
        
        private string distancetypeField;
        
        private string featureclass_idField;
        
        private string levelField;
        
        private string searchtextField;
        
        private string sessionidField;
        
        private string useridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currentlocation
        {
            get
            {
                return this.currentlocationField;
            }
            set
            {
                this.currentlocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distancetype
        {
            get
            {
                return this.distancetypeField;
            }
            set
            {
                this.distancetypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string featureclass_id
        {
            get
            {
                return this.featureclass_idField;
            }
            set
            {
                this.featureclass_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string searchtext
        {
            get
            {
                return this.searchtextField;
            }
            set
            {
                this.searchtextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sessionid
        {
            get
            {
                return this.sessionidField;
            }
            set
            {
                this.sessionidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QiblaInput", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class QiblaInput : object
    {
        
        private string LocationField;
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USERACTIVITY", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class USERACTIVITY : object
    {
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZNG_REGULATION", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ZNG_REGULATION : object
    {
        
        private string LandnoField;
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Landno
        {
            get
            {
                return this.LandnoField;
            }
            set
            {
                this.LandnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SHARELOCATION", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SHARELOCATION : object
    {
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string NameField;
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GETLOCATION", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class GETLOCATION : object
    {
        
        private string DbSeqNoField;
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DbSeqNo
        {
            get
            {
                return this.DbSeqNoField;
            }
            set
            {
                this.DbSeqNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SAVEFAVORITES", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SAVEFAVORITES : object
    {
        
        private string FavNameField;
        
        private string FavTypeField;
        
        private string FavValueField;
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavName
        {
            get
            {
                return this.FavNameField;
            }
            set
            {
                this.FavNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavType
        {
            get
            {
                return this.FavTypeField;
            }
            set
            {
                this.FavTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavValue
        {
            get
            {
                return this.FavValueField;
            }
            set
            {
                this.FavValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDITFAVORITES", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class EDITFAVORITES : object
    {
        
        private string FavNameNewField;
        
        private string FavNameOldField;
        
        private string FavTypeField;
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavNameNew
        {
            get
            {
                return this.FavNameNewField;
            }
            set
            {
                this.FavNameNewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavNameOld
        {
            get
            {
                return this.FavNameOldField;
            }
            set
            {
                this.FavNameOldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavType
        {
            get
            {
                return this.FavTypeField;
            }
            set
            {
                this.FavTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DELETFAVORITES", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class DELETFAVORITES : object
    {
        
        private string FavNameField;
        
        private string FavTypeField;
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavName
        {
            get
            {
                return this.FavNameField;
            }
            set
            {
                this.FavNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavType
        {
            get
            {
                return this.FavTypeField;
            }
            set
            {
                this.FavTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GETFAVORITES", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class GETFAVORITES : object
    {
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UPDATE_USERDETAILS_INPUT", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class UPDATE_USERDETAILS_INPUT : object
    {
        
        private string AddressField;
        
        private string EmailField;
        
        private string GenderField;
        
        private string LangField;
        
        private string NameField;
        
        private string PhoneNumberField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SYNCFAVOURITES", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SYNCFAVOURITES : object
    {
        
        private MakaniNumberService.FAVOURITE[] FavoritesField;
        
        private string SessionIdField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MakaniNumberService.FAVOURITE[] Favorites
        {
            get
            {
                return this.FavoritesField;
            }
            set
            {
                this.FavoritesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FAVOURITE", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class FAVOURITE : object
    {
        
        private string BuildingNameAField;
        
        private string BuildingNameEField;
        
        private string FavIdField;
        
        private string FavNameField;
        
        private string FavTypeField;
        
        private string FavValueField;
        
        private bool IsMyMakaniField;
        
        private string LastUpdatedField;
        
        private string LocationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNameA
        {
            get
            {
                return this.BuildingNameAField;
            }
            set
            {
                this.BuildingNameAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNameE
        {
            get
            {
                return this.BuildingNameEField;
            }
            set
            {
                this.BuildingNameEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavId
        {
            get
            {
                return this.FavIdField;
            }
            set
            {
                this.FavIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavName
        {
            get
            {
                return this.FavNameField;
            }
            set
            {
                this.FavNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavType
        {
            get
            {
                return this.FavTypeField;
            }
            set
            {
                this.FavTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavValue
        {
            get
            {
                return this.FavValueField;
            }
            set
            {
                this.FavValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMyMakani
        {
            get
            {
                return this.IsMyMakaniField;
            }
            set
            {
                this.IsMyMakaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifyMyIdLoginInput", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class NotifyMyIdLoginInput : object
    {
        
        private string AccountLockField;
        
        private string DobField;
        
        private string EmailField;
        
        private string EmailVerifiedField;
        
        private string FirstNameField;
        
        private string FirstNameArField;
        
        private string FullNameField;
        
        private string FullNameArField;
        
        private string GenderField;
        
        private string IdCardExpiryDateField;
        
        private string IdCardIssueDateField;
        
        private string IdCardNumberField;
        
        private string IdnField;
        
        private string LastNameField;
        
        private string LastNameArField;
        
        private string MaritalStatusField;
        
        private string MobileField;
        
        private string NationalityField;
        
        private string NationalityArField;
        
        private string PassportCountryField;
        
        private string PassportExpiryDateField;
        
        private string PassportIssueDateField;
        
        private string PassportNoField;
        
        private string PhotoField;
        
        private string PhotoUrlField;
        
        private string ResidencyExpiryDateField;
        
        private string ResidencyNoField;
        
        private string SourceField;
        
        private string SponsorNoField;
        
        private string SponsorTypeField;
        
        private string UserIdField;
        
        private string UserNameField;
        
        private string UserVerifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountLock
        {
            get
            {
                return this.AccountLockField;
            }
            set
            {
                this.AccountLockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dob
        {
            get
            {
                return this.DobField;
            }
            set
            {
                this.DobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailVerified
        {
            get
            {
                return this.EmailVerifiedField;
            }
            set
            {
                this.EmailVerifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameAr
        {
            get
            {
                return this.FirstNameArField;
            }
            set
            {
                this.FirstNameArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameAr
        {
            get
            {
                return this.FullNameArField;
            }
            set
            {
                this.FullNameArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCardExpiryDate
        {
            get
            {
                return this.IdCardExpiryDateField;
            }
            set
            {
                this.IdCardExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCardIssueDate
        {
            get
            {
                return this.IdCardIssueDateField;
            }
            set
            {
                this.IdCardIssueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCardNumber
        {
            get
            {
                return this.IdCardNumberField;
            }
            set
            {
                this.IdCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idn
        {
            get
            {
                return this.IdnField;
            }
            set
            {
                this.IdnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNameAr
        {
            get
            {
                return this.LastNameArField;
            }
            set
            {
                this.LastNameArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus
        {
            get
            {
                return this.MaritalStatusField;
            }
            set
            {
                this.MaritalStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                this.NationalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityAr
        {
            get
            {
                return this.NationalityArField;
            }
            set
            {
                this.NationalityArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportCountry
        {
            get
            {
                return this.PassportCountryField;
            }
            set
            {
                this.PassportCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportExpiryDate
        {
            get
            {
                return this.PassportExpiryDateField;
            }
            set
            {
                this.PassportExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportIssueDate
        {
            get
            {
                return this.PassportIssueDateField;
            }
            set
            {
                this.PassportIssueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNo
        {
            get
            {
                return this.PassportNoField;
            }
            set
            {
                this.PassportNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoUrl
        {
            get
            {
                return this.PhotoUrlField;
            }
            set
            {
                this.PhotoUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidencyExpiryDate
        {
            get
            {
                return this.ResidencyExpiryDateField;
            }
            set
            {
                this.ResidencyExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidencyNo
        {
            get
            {
                return this.ResidencyNoField;
            }
            set
            {
                this.ResidencyNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorNo
        {
            get
            {
                return this.SponsorNoField;
            }
            set
            {
                this.SponsorNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorType
        {
            get
            {
                return this.SponsorTypeField;
            }
            set
            {
                this.SponsorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserVerified
        {
            get
            {
                return this.UserVerifiedField;
            }
            set
            {
                this.UserVerifiedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifySocialMediaLoginInput", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class NotifySocialMediaLoginInput : object
    {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string PhotoUrlField;
        
        private string SocialMediaUserIdField;
        
        private string SourceField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoUrl
        {
            get
            {
                return this.PhotoUrlField;
            }
            set
            {
                this.PhotoUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialMediaUserId
        {
            get
            {
                return this.SocialMediaUserIdField;
            }
            set
            {
                this.SocialMediaUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifyUAEPASSUserLoginInput", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class NotifyUAEPASSUserLoginInput : object
    {
        
        private string domainField;
        
        private string emailField;
        
        private string firstnameARField;
        
        private string firstnameENField;
        
        private string fullnameARField;
        
        private string fullnameENField;
        
        private string genderField;
        
        private string idTypeField;
        
        private string idnField;
        
        private string lastnameARField;
        
        private string lastnameENField;
        
        private string mobileField;
        
        private string nationalityARField;
        
        private string nationalityENField;
        
        private string subField;
        
        private string userTypeField;
        
        private string uuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstnameAR
        {
            get
            {
                return this.firstnameARField;
            }
            set
            {
                this.firstnameARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstnameEN
        {
            get
            {
                return this.firstnameENField;
            }
            set
            {
                this.firstnameENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullnameAR
        {
            get
            {
                return this.fullnameARField;
            }
            set
            {
                this.fullnameARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullnameEN
        {
            get
            {
                return this.fullnameENField;
            }
            set
            {
                this.fullnameENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idType
        {
            get
            {
                return this.idTypeField;
            }
            set
            {
                this.idTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idn
        {
            get
            {
                return this.idnField;
            }
            set
            {
                this.idnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastnameAR
        {
            get
            {
                return this.lastnameARField;
            }
            set
            {
                this.lastnameARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastnameEN
        {
            get
            {
                return this.lastnameENField;
            }
            set
            {
                this.lastnameENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nationalityAR
        {
            get
            {
                return this.nationalityARField;
            }
            set
            {
                this.nationalityARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nationalityEN
        {
            get
            {
                return this.nationalityENField;
            }
            set
            {
                this.nationalityENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sub
        {
            get
            {
                return this.subField;
            }
            set
            {
                this.subField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkUAEPASSAndSocialMediaUserInput", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class LinkUAEPASSAndSocialMediaUserInput : object
    {
        
        private MakaniNumberService.SocialMedia SocialMediaField;
        
        private MakaniNumberService.NotifyUAEPASSUserLoginInput UAEPASSField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MakaniNumberService.SocialMedia SocialMedia
        {
            get
            {
                return this.SocialMediaField;
            }
            set
            {
                this.SocialMediaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MakaniNumberService.NotifyUAEPASSUserLoginInput UAEPASS
        {
            get
            {
                return this.UAEPASSField;
            }
            set
            {
                this.UAEPASSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialMedia", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SocialMedia : object
    {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string PhotoUrlField;
        
        private string SocialMediaUserIdField;
        
        private string SourceField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoUrl
        {
            get
            {
                return this.PhotoUrlField;
            }
            set
            {
                this.PhotoUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialMediaUserId
        {
            get
            {
                return this.SocialMediaUserIdField;
            }
            set
            {
                this.SocialMediaUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MakaniNumberService.IMakaniPhase2Proxy")]
    public interface IMakaniPhase2Proxy
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetOptions", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetOptionsResponse")]
        System.Threading.Tasks.Task GetOptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/SignUp", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/SignUpResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> SignUpAsync(MakaniNumberService.SIGNUP InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/MakaniLogin", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/MakaniLoginResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> MakaniLoginAsync(MakaniNumberService.LOGIN InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/ForgotPassword", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/ForgotPasswordResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ForgotPasswordAsync(MakaniNumberService.FORGETPASSWORD InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/ResetPassword", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/ResetPasswordResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ResetPasswordAsync(MakaniNumberService.RESETPASSWORD InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/MakaniLogOut", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/MakaniLogOutResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> MakaniLogOutAsync(MakaniNumberService.LOGOUT InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/SmartSearch", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/SmartSearchResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> SmartSearchAsync(MakaniNumberService.SearchInput InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/SmartSearchResult", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/SmartSearchResultResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> SmartSearchResultAsync(MakaniNumberService.SearchResult InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetVirtualPlate", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetVirtualPlateResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetVirtualPlateAsync(MakaniNumberService.VirtualPlateInput InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetQiblaDirection", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetQiblaDirectionResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetQiblaDirectionAsync(MakaniNumberService.QiblaInput InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetPublicActivities", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetPublicActivitiesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetPublicActivitiesAsync(string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetUserActivities", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetUserActivitiesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetUserActivitiesAsync(MakaniNumberService.USERACTIVITY InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetZoningRegulation", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetZoningRegulationResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetZoningRegulationAsync(MakaniNumberService.ZNG_REGULATION InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/ShareLocation", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/ShareLocationResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ShareLocationAsync(MakaniNumberService.SHARELOCATION InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetLocation", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetLocationResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetLocationAsync(MakaniNumberService.GETLOCATION InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/SaveFavorites", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/SaveFavoritesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> SaveFavoritesAsync(MakaniNumberService.SAVEFAVORITES InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/EditFavorites", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/EditFavoritesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> EditFavoritesAsync(MakaniNumberService.EDITFAVORITES InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/DeleteFavorites", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/DeleteFavoritesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DeleteFavoritesAsync(MakaniNumberService.DELETFAVORITES InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetFavorites", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetFavoritesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetFavoritesAsync(MakaniNumberService.GETFAVORITES InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/UpdateMakaniUserDetails", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/UpdateMakaniUserDetailsResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> UpdateMakaniUserDetailsAsync(MakaniNumberService.UPDATE_USERDETAILS_INPUT InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetPOIInfo", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetPOIInfoResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetPOIInfoAsync(string Poiname, string Lang, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetMakaniNoNew", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetMakaniNoNewResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetMakaniNoNewAsync(string Makaninumber, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetBuildingInfo", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetBuildingInfoResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetBuildingInfoAsync(string Makaninumber, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetAllCommunities", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetAllCommunitiesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetAllCommunitiesAsync(string CommName, string Lang, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetStreetsFromCommunity", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetStreetsFromCommunityResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetStreetsFromCommunityAsync(string CommunityName, string StreetName, string Lang, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetBuildingsList", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetBuildingsListResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetBuildingsListAsync(string CommunityName, string StreetName, string Lang, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetBuildingAddress", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetBuildingAddressResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetBuildingAddressAsync(string CommunityName, string StreetName, string BuildingName, string Lang, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetBuildingOutLine_EntrancePoints", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetBuildingOutLine_EntrancePointsResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetBuildingOutLine_EntrancePointsAsync(string Lat, string Lng, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetParcelOutline_New", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetParcelOutline_NewResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetParcelOutline_NewAsync(string ParcelId, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/CoordinateConversionNew", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/CoordinateConversionNewResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> CoordinateConversionNewAsync(string Type, string CoordinateX, string CoordinateY, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/DMSToCoordinatesNew", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/DMSToCoordinatesNewResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DMSToCoordinatesNewAsync(string DegLat, string MinLat, string SecLat, string DegLng, string MinLng, string SecLng, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/SyncFavourites", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/SyncFavouritesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> SyncFavouritesAsync(MakaniNumberService.SYNCFAVOURITES InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetAllPOICategories", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetAllPOICategoriesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetAllPOICategoriesAsync(string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/GetAllPOIsOfCategories", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/GetAllPOIsOfCategoriesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetAllPOIsOfCategoriesAsync(string CategorieIds, string LatLng, string WithInDistance, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/NotifyMyIdUserLogin", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/NotifyMyIdUserLoginResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> NotifyMyIdUserLoginAsync(MakaniNumberService.NotifyMyIdLoginInput InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/NotifySocialMediaUserLogin", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/NotifySocialMediaUserLoginResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> NotifySocialMediaUserLoginAsync(MakaniNumberService.NotifySocialMediaLoginInput InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/NotifyUAEPASSUserLogin", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/NotifyUAEPASSUserLoginResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> NotifyUAEPASSUserLoginAsync(MakaniNumberService.NotifyUAEPASSUserLoginInput InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/ValidUAEPASSUser", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/ValidUAEPASSUserResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ValidUAEPASSUserAsync(MakaniNumberService.NotifyUAEPASSUserLoginInput InputJson, string Token, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPhase2Proxy/LinkUAEPASSAndSocialMediaUser", ReplyAction="http://tempuri.org/IMakaniPhase2Proxy/LinkUAEPASSAndSocialMediaUserResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> LinkUAEPASSAndSocialMediaUserAsync(MakaniNumberService.LinkUAEPASSAndSocialMediaUserInput InputJson, string Token, string Remarks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IMakaniPhase2ProxyChannel : MakaniNumberService.IMakaniPhase2Proxy, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MakaniPhase2ProxyClient : System.ServiceModel.ClientBase<MakaniNumberService.IMakaniPhase2Proxy>, MakaniNumberService.IMakaniPhase2Proxy
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MakaniPhase2ProxyClient() : 
                base(MakaniPhase2ProxyClient.GetDefaultBinding(), MakaniPhase2ProxyClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMakaniPhase2Proxy.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MakaniPhase2ProxyClient(EndpointConfiguration endpointConfiguration) : 
                base(MakaniPhase2ProxyClient.GetBindingForEndpoint(endpointConfiguration), MakaniPhase2ProxyClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MakaniPhase2ProxyClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MakaniPhase2ProxyClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MakaniPhase2ProxyClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MakaniPhase2ProxyClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MakaniPhase2ProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task GetOptionsAsync()
        {
            return base.Channel.GetOptionsAsync();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> SignUpAsync(MakaniNumberService.SIGNUP InputJson, string Token, string Remarks)
        {
            return base.Channel.SignUpAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> MakaniLoginAsync(MakaniNumberService.LOGIN InputJson, string Token, string Remarks)
        {
            return base.Channel.MakaniLoginAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ForgotPasswordAsync(MakaniNumberService.FORGETPASSWORD InputJson, string Token, string Remarks)
        {
            return base.Channel.ForgotPasswordAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ResetPasswordAsync(MakaniNumberService.RESETPASSWORD InputJson, string Token, string Remarks)
        {
            return base.Channel.ResetPasswordAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> MakaniLogOutAsync(MakaniNumberService.LOGOUT InputJson, string Token, string Remarks)
        {
            return base.Channel.MakaniLogOutAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> SmartSearchAsync(MakaniNumberService.SearchInput InputJson, string Token, string Remarks)
        {
            return base.Channel.SmartSearchAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> SmartSearchResultAsync(MakaniNumberService.SearchResult InputJson, string Token, string Remarks)
        {
            return base.Channel.SmartSearchResultAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetVirtualPlateAsync(MakaniNumberService.VirtualPlateInput InputJson, string Token, string Remarks)
        {
            return base.Channel.GetVirtualPlateAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetQiblaDirectionAsync(MakaniNumberService.QiblaInput InputJson, string Token, string Remarks)
        {
            return base.Channel.GetQiblaDirectionAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetPublicActivitiesAsync(string Token, string Remarks)
        {
            return base.Channel.GetPublicActivitiesAsync(Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetUserActivitiesAsync(MakaniNumberService.USERACTIVITY InputJson, string Token, string Remarks)
        {
            return base.Channel.GetUserActivitiesAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetZoningRegulationAsync(MakaniNumberService.ZNG_REGULATION InputJson, string Token, string Remarks)
        {
            return base.Channel.GetZoningRegulationAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ShareLocationAsync(MakaniNumberService.SHARELOCATION InputJson, string Token, string Remarks)
        {
            return base.Channel.ShareLocationAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetLocationAsync(MakaniNumberService.GETLOCATION InputJson, string Token, string Remarks)
        {
            return base.Channel.GetLocationAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> SaveFavoritesAsync(MakaniNumberService.SAVEFAVORITES InputJson, string Token, string Remarks)
        {
            return base.Channel.SaveFavoritesAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> EditFavoritesAsync(MakaniNumberService.EDITFAVORITES InputJson, string Token, string Remarks)
        {
            return base.Channel.EditFavoritesAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DeleteFavoritesAsync(MakaniNumberService.DELETFAVORITES InputJson, string Token, string Remarks)
        {
            return base.Channel.DeleteFavoritesAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetFavoritesAsync(MakaniNumberService.GETFAVORITES InputJson, string Token, string Remarks)
        {
            return base.Channel.GetFavoritesAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> UpdateMakaniUserDetailsAsync(MakaniNumberService.UPDATE_USERDETAILS_INPUT InputJson, string Token, string Remarks)
        {
            return base.Channel.UpdateMakaniUserDetailsAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetPOIInfoAsync(string Poiname, string Lang, string Token, string Remarks)
        {
            return base.Channel.GetPOIInfoAsync(Poiname, Lang, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetMakaniNoNewAsync(string Makaninumber, string Token, string Remarks)
        {
            return base.Channel.GetMakaniNoNewAsync(Makaninumber, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetBuildingInfoAsync(string Makaninumber, string Token, string Remarks)
        {
            return base.Channel.GetBuildingInfoAsync(Makaninumber, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetAllCommunitiesAsync(string CommName, string Lang, string Token, string Remarks)
        {
            return base.Channel.GetAllCommunitiesAsync(CommName, Lang, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetStreetsFromCommunityAsync(string CommunityName, string StreetName, string Lang, string Token, string Remarks)
        {
            return base.Channel.GetStreetsFromCommunityAsync(CommunityName, StreetName, Lang, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetBuildingsListAsync(string CommunityName, string StreetName, string Lang, string Token, string Remarks)
        {
            return base.Channel.GetBuildingsListAsync(CommunityName, StreetName, Lang, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetBuildingAddressAsync(string CommunityName, string StreetName, string BuildingName, string Lang, string Token, string Remarks)
        {
            return base.Channel.GetBuildingAddressAsync(CommunityName, StreetName, BuildingName, Lang, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetBuildingOutLine_EntrancePointsAsync(string Lat, string Lng, string Token, string Remarks)
        {
            return base.Channel.GetBuildingOutLine_EntrancePointsAsync(Lat, Lng, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetParcelOutline_NewAsync(string ParcelId, string Token, string Remarks)
        {
            return base.Channel.GetParcelOutline_NewAsync(ParcelId, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> CoordinateConversionNewAsync(string Type, string CoordinateX, string CoordinateY, string Token, string Remarks)
        {
            return base.Channel.CoordinateConversionNewAsync(Type, CoordinateX, CoordinateY, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DMSToCoordinatesNewAsync(string DegLat, string MinLat, string SecLat, string DegLng, string MinLng, string SecLng, string Token, string Remarks)
        {
            return base.Channel.DMSToCoordinatesNewAsync(DegLat, MinLat, SecLat, DegLng, MinLng, SecLng, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> SyncFavouritesAsync(MakaniNumberService.SYNCFAVOURITES InputJson, string Token, string Remarks)
        {
            return base.Channel.SyncFavouritesAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetAllPOICategoriesAsync(string Token, string Remarks)
        {
            return base.Channel.GetAllPOICategoriesAsync(Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetAllPOIsOfCategoriesAsync(string CategorieIds, string LatLng, string WithInDistance, string Token, string Remarks)
        {
            return base.Channel.GetAllPOIsOfCategoriesAsync(CategorieIds, LatLng, WithInDistance, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> NotifyMyIdUserLoginAsync(MakaniNumberService.NotifyMyIdLoginInput InputJson, string Token, string Remarks)
        {
            return base.Channel.NotifyMyIdUserLoginAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> NotifySocialMediaUserLoginAsync(MakaniNumberService.NotifySocialMediaLoginInput InputJson, string Token, string Remarks)
        {
            return base.Channel.NotifySocialMediaUserLoginAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> NotifyUAEPASSUserLoginAsync(MakaniNumberService.NotifyUAEPASSUserLoginInput InputJson, string Token, string Remarks)
        {
            return base.Channel.NotifyUAEPASSUserLoginAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ValidUAEPASSUserAsync(MakaniNumberService.NotifyUAEPASSUserLoginInput InputJson, string Token, string Remarks)
        {
            return base.Channel.ValidUAEPASSUserAsync(InputJson, Token, Remarks);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> LinkUAEPASSAndSocialMediaUserAsync(MakaniNumberService.LinkUAEPASSAndSocialMediaUserInput InputJson, string Token, string Remarks)
        {
            return base.Channel.LinkUAEPASSAndSocialMediaUserAsync(InputJson, Token, Remarks);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMakaniPhase2Proxy))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMakaniPhase2Proxy))
            {
                return new System.ServiceModel.EndpointAddress("https://www.makani.ae/MakaniPhase2ProxyWebService/MakaniPhase2Proxy.svc/basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MakaniPhase2ProxyClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMakaniPhase2Proxy);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MakaniPhase2ProxyClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMakaniPhase2Proxy);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMakaniPhase2Proxy,
        }
    }
}
