//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakaniPublic
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMakaniPublic")]
    public interface IMakaniPublic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPublic/GetMakaniInfoFromCoord", ReplyAction="http://tempuri.org/IMakaniPublic/GetMakaniInfoFromCoordResponse")]
        System.Threading.Tasks.Task<string> GetMakaniInfoFromCoordAsync(string latitude, string longitude, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPublic/GetMakaniDetails", ReplyAction="http://tempuri.org/IMakaniPublic/GetMakaniDetailsResponse")]
        System.Threading.Tasks.Task<string> GetMakaniDetailsAsync(string makanino, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPublic/IsValidMakani", ReplyAction="http://tempuri.org/IMakaniPublic/IsValidMakaniResponse")]
        System.Threading.Tasks.Task<string> IsValidMakaniAsync(string makanino, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMakaniPublic/GetQRCodeForMakani", ReplyAction="http://tempuri.org/IMakaniPublic/GetQRCodeForMakaniResponse")]
        System.Threading.Tasks.Task<string> GetQRCodeForMakaniAsync(string makanino, string remarks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IMakaniPublicChannel : MakaniPublic.IMakaniPublic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MakaniPublicClient : System.ServiceModel.ClientBase<MakaniPublic.IMakaniPublic>, MakaniPublic.IMakaniPublic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MakaniPublicClient() : 
                base(MakaniPublicClient.GetDefaultBinding(), MakaniPublicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMakaniPublic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MakaniPublicClient(EndpointConfiguration endpointConfiguration) : 
                base(MakaniPublicClient.GetBindingForEndpoint(endpointConfiguration), MakaniPublicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MakaniPublicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MakaniPublicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MakaniPublicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MakaniPublicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MakaniPublicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetMakaniInfoFromCoordAsync(string latitude, string longitude, string remarks)
        {
            return base.Channel.GetMakaniInfoFromCoordAsync(latitude, longitude, remarks);
        }
        
        public System.Threading.Tasks.Task<string> GetMakaniDetailsAsync(string makanino, string remarks)
        {
            return base.Channel.GetMakaniDetailsAsync(makanino, remarks);
        }
        
        public System.Threading.Tasks.Task<string> IsValidMakaniAsync(string makanino, string remarks)
        {
            return base.Channel.IsValidMakaniAsync(makanino, remarks);
        }
        
        public System.Threading.Tasks.Task<string> GetQRCodeForMakaniAsync(string makanino, string remarks)
        {
            return base.Channel.GetQRCodeForMakaniAsync(makanino, remarks);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMakaniPublic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMakaniPublic))
            {
                return new System.ServiceModel.EndpointAddress("https://www.makani.ae/MakaniPublicDataService/MakaniPublic.svc/basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MakaniPublicClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMakaniPublic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MakaniPublicClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMakaniPublic);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMakaniPublic,
        }
    }
}
